name: "Build"

on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Set up Deno"
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: "Check with Deno"
        run: |
          deno check

      - name: "Build with Deno"
        run: |
          deno task build

      - uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: ./build/libs/
