name: "Deploy"

on:
  push:
    branches: [ "data" ]
  # Allows to run this workflow manually.
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Setup Deno"
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: "Build with Deno"
        run: |
          ./build.sh
      - name: "Deploy README"
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: rendered
          folder: build
      - name: "Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: pages
          path: ./build
          retention-days: 1
          if-no-files-found: error

  deploy:
    needs: build
    runs-on: ubuntu-latest

    # Deploy to the pages environment
    environment:
      name: pages
      url: "https://optifine.alternatives.lambdaurora.dev/"

    permissions:
      contents: read
      deployments: write

    steps:
      - name: "Download artifacts"
        uses: actions/download-artifact@v3
        with:
          name: pages
          path: dist
      - name: "Publish to Cloudflare Pages"
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: optifine-alternatives
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
